#!/bin/bash

install_brewfile() {
    # Install packages from Brewfile (generated by Alchemist)
    if [[ "$HOSTNAME" == "mbp-justin" ]]; then
        brew bundle --file "$HOME/.dotfiles/src/personal/Brewfile"
    elif [[ "$HOSTNAME" == "Server2" ]]; then
        brew bundle --file "$HOME/.dotfiles/src/server2/Brewfile"
    elif [[ "$HOSTNAME" == "mbp-justin-ep" ]]; then
        brew bundle --file "$HOME/.dotfiles/src/easypost/Brewfile"
    else
        echo "HOSTNAME doesn't match any config for Brewfile installation."
    fi
}

install_brewfile
