@echo off
choco install 1password
choco install 7zip
choco install 7zip.install
choco install ccleaner
choco install chocolatey
choco install chocolatey-core.extension
choco install chocolatey-dotnetfx.extension
choco install chocolatey-windowsupdate.extension
choco install DotNet4.5.2
choco install dotnet4.7.2
choco install dotnetfx
choco install git
choco install git.install
choco install golang
choco install GoogleChrome
choco install jq
choco install KB2919355
choco install KB2919442
choco install KB2999226
choco install KB3033929
choco install KB3035131
choco install malwarebytes
choco install microsoft-windows-terminal
choco install playnite
choco install python
choco install python3
choco install vcredist140
choco install vcredist2015
choco install vscode
choco install vscode.install
