name: build

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.0.0
        env:
          SHELLCHECK_OPTS: -e SC2148 -e SC1090 -e SC2034
