name: build

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run ShellCheck on /src/scripts
        uses: ludeeus/action-shellcheck@1.0.0
        env:
          SHELLCHECK_OPTS: src/scripts/*.sh
      - name: Run ShellCheck on /src/core
        uses: ludeeus/action-shellcheck@1.0.0
        env:
          SHELLCHECK_OPTS: src/core/*.sh
